# Generated by Django 2.0 on 2020-08-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
